language: python
cache: packages
install:
  - ./.testing/install-ci.sh
 # - PATH=$PATH:$PWD/tools/bin # might not be appropriate for users to add to their PATH
# Install R packages
  - tools/bin/Rscript --verbose ./.testing/install-packages.R
# Create working directory
  - mkdir test
  - cp reference-data/SCA8_region.bed test/
  - cd test/
# command to run tests
script:
# Run the test data
- ../tools/bin/bpipe run ../pipelines/STRetch_exome_pipeline.groovy ../test-data/*.fastq.gz
after_script:
- head *.locus_counts *.STR_counts *.median_cov
- head *.tsv
