name: STR
channels:
- conda-forge
- bioconda
dependencies:
# Python
- python=3*
- BioPython
- PyVCF
- pysam
- pandas
- statsmodels
- scikit-learn
# pinning scipy to avoid factorial import error, until statsmodels fixes it
- scipy=1.2
- numpy
- pybedtools
# only required for development
- pytest
- coverage
# command line tools
- bedtools
- htslib
- goleft=0.1.8
- mosdepth
